species_table: "config/species.csv"

hifiasm:
  threads: 32
  extra: ""

compleasm:
  lineage: eudicotyledons_odb12
  library_path: mb_downloads 

genomescope2:
  threads: 16
  hash_size: 20000000000

blobtoolkit:
  blastn_nal: /netscratch/dep_mercier/grp_marques/Aaryan/blastdb_local/ncbi/nt.nal
  blastp_dmnd: /opt/share/blastdb/ncbi-diamond/nr.dmnd
  blastx_dmnd: /opt/share/blastdb/ncbi-diamond/nr.dmnd
  taxdump: /opt/share/blastdb/taxonomy/new_taxdump
  nextflow_work_base: /netscratch/dep_mercier/grp_marques/Aaryan/reproducible_phd/nextflow_work
  nextflow_revision: 0.10.1
