species_table: "config/species.csv"

hifiasm:
  threads: 32
  extra: ""

compleasm:
  lineage: eudicotyledons_odb12
  library_path: mb_downloads 

genomescope2:
  threads: 16
  hash_size: 20000000000
